### ISSUE TITLE
1.0 Ship List

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/cadence#16]
### Front end
- [ ] Single page application using Backbone.js, Compass/SASS, and Bootstrap 4
- [ ] Make use of [Ictus UI framework](https://github.com/chimericdream/ictus) to decouple custom Bootstrap tweaks from main app (Cadence 1.0 and Ictus 1.0 releases should coincide)
### Account management
- [x] Allow multiple accounts for a given plugin (#15)
### Data management
- [x] Define data models not directly associated with a plugin
- [x] Modify data model states via REST API
- [ ] Allow plugins/components to store their own data
- [ ] Create relationships between two entities for two-way data binding (e.g. Toodledo task due date <--> Google Calendar event)
- [ ] Data stored in reliable and fast database (MongoDB, SQLite, etc; exact choice TBD)
### Workflows
- [ ] Create connections between systems (1-to-1 or 1-to-many)
- [ ] Schedule and event based processes
- [ ] Conditional logic
- [ ] Iterative logic
- [ ] Data transformation (e.g. regular expressions or key/value multiplexing)
### Features
- [ ] Present system logs to user in a usable fashion
- [ ] Customizable "dashboard" for the home page, where a user can put widgets with graphs, log info, etc
### Build
- [ ] Compile SASS files to a single CSS file
- [ ] Compile front end JS to a single file
- [ ] Run ESLint
- [ ] Run SASS Lint
- [ ] Run Karma/Mocha tests
- [ ] Build core documentation
- [ ] Generate API docs from docblocks
### Documentation
- [ ] List plugins included with the app
- [ ] List read/write actions each plugins can perform
- [ ] Documentation (#20)
  - [ ] List example solutions that can be built with the app
