### ISSUE TITLE
0.1.0-alpha Ship List

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/cadence#21]
#### Features
- [x] Data Shards
  - [x] Create a shard
  - [x] Modify a shard's value from the app
  - [x] Modify a shard's value via the API
  - [x] Get a shard's value via the API
  - [x] View the complete data history of a shard from the app
  - [x] Get a shard's history via the API
  - [x] ~~Delete a shard~~ (moved to 0.2.0)
- [x] Accounts
  - [x] Add account
  - [x] ~~Delete account~~ (moved to 0.2.0)
  - [x] ~~View all data associated with an account from the app~~ (moved to 0.2.0)
  - [x] Get all data associated with an account via the API
