### ISSUE TITLE
0.2.0-alpha Ship List

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/cadence#24]
#### Misc
- [x] Error handling for data files (#23)
- [x] Split front/back end (#22)
- [x] Audit code to use `js-*` classes for dynamic behavior (#25)
#### Features
- [x] Data Shards
  - [x] Delete a shard
  - [x] Create a shard if it doesn't exist on update (#29)
- [x] Accounts
  - [x] Delete account
  - [x] View all data associated with an account from the app
