### ISSUE TITLE
0.3.0-alpha Ship List

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/cadence#26]
### Features
- [x] Explicitly start using Ictus CSS
- [x] ~~Graphs for visualizing shard history (where applicable)~~ (punting)
- [x] ~~Dashboard widgets~~ (punting)

### Refactoring
- [x] Use Marionette Views/Regions/Sub-Views for rendering parts of a page
